apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Trino
    type: grafana-trino-datasource
    access: proxy
    url: http://trino:8080
    editable: false
    jsonData:
      catalog: iceberg
      schema: gold
